process:
  name: "plan-and-execute-article-v1"
  start: "planner"
  done_condition: "artifacts.final_article is not None"

agents:
  planner:
    kind: "llm"
    purpose: "Criar um plano passo a passo para escrever um artigo sobre um tópico."
    model_name: "gemini-1.5-flash"
    prompt_template: |
      Crie um plano detalhado para escrever um artigo sobre '{context[topic]}'.
      O plano deve incluir etapas como pesquisa, esboço, redação de seções e revisão.
      Retorne o plano como uma lista de strings em um JSON com a chave "plan".
    output_key: "plan"
    force_json_output: true

  executor:
    kind: "tool_using"
    purpose: "Executar uma etapa do plano de escrita, usando ferramentas se necessário."
    model_name: "gemini-1.5-pro"
    tools: ["tavily_search"] # Ferramenta de pesquisa para a etapa de pesquisa
    prompt_template: |
      Você é um assistente de escrita. Sua tarefa atual é: {artifacts[plan][0]}.
      Use as ferramentas disponíveis se precisar de informações.
      Contexto atual: {context}
      Artefatos já criados: {artifacts}
    output_key: "step_result"

  updater:
    kind: "deterministic"
    purpose: "Atualizar o estado do processo com o resultado da etapa e remover a etapa concluída do plano."
    function: "update_plan_and_artifacts" # (Esta função precisaria ser adicionada ao ToolRegistry)

  finalizer:
    kind: "llm"
    purpose: "Consolidar todos os resultados em um artigo final."
    model_name: "gpt-4o"
    prompt_template: "Com base nos resultados {artifacts[step_results]}, escreva o artigo final sobre '{context[topic]}'."
    output_key: "final_article"

edges:
  - { from: "planner", to: "executor", condition: "artifacts.plan is not None" }
  - { from: "executor", to: "updater" }
  - { from: "updater", to: "executor", condition: "artifacts.plan and len(artifacts.plan) > 0" }
  - { from: "updater", to: "finalizer", condition: "artifacts.plan is None or len(artifacts.plan) == 0" }
  - { from: "finalizer", to: "__end__" }